added folder Hometask4
ohurtova/KH-044-QA-06-Hurtova-Olha pull request #4
Opened 2021-09-07 18:26 UTC by ohurtova

Привет. код вроде работает, но в некоторых случаях екзится после ввода последующего фильтра. Можешь, пожалуйста, подсказать, в чем ошибка?

2021-09-10 14:16 UTC, tiggggggo commented on Hometask4/src/hometask4.java
> +                            filter++;
переменная фильтр сохраняет выбранный номер фильтра
зачем при переборе каждого слова эту переменную увеличивать на один?

2021-09-10 14:18 UTC, tiggggggo commented on Hometask4/src/hometask4.java
> +        } while (filter < 5);
переменная фильтр сохраняет выбранный номер фильтра
зачем то при переборе каждого слова эту переменную увеличиваешь на один

из-за этого переменная фильтра почти всегда выходит больше 5

2021-09-13 10:22 UTC, tiggggggo requested changes
в коде есть ошибки компиляции, он не запускается, исправь их

2021-09-13 10:30 UTC, ohurtova commented
Блин... такая дурная ошибка 😅 исправлю сразу по приходу домой)

2021-09-13 18:36 UTC, tiggggggo commented on Hometask4/src/hometask4.java
> +                        }
длина должна быть меньше либо равно максимальной длине введенного сичла

2021-09-13 18:36 UTC, tiggggggo commented on Hometask4/src/hometask4.java
> +        do { filter = scanner.nextInt();
код выбора фильтра надо переместить в блок do, чтобы было понятно что выбирать на втором круге

2021-09-14 06:42 UTC, tiggggggo reviewed
test comment

2021-09-16 11:15 UTC, tiggggggo approved these changes

2021-09-16 15:03 UTC, merged